image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run build

deploy_to_s3:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync ./build/ s3://www.southwesthurricaneaid.me/ --delete
  only:
    - master
