image: node:latest
before_script:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
stages:
  - build
  - deploy

cache:
  paths:
    - frontend/node_modules/

install_dependencies:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./frontend/build/
  only:
    - prod

deploy_to_s3:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - aws s3 sync ./frontend/build/ s3://www.southwesthurricaneaid.me/ --delete
  only:
    - prod
